repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: lint
        name: Run all linters
        entry: make lint
        pass_filenames: false
        language: system
        types: [python]
      - id: test
        name: Run all tests
        entry: make test
        pass_filenames: false
        language: system
        types: [python]
